# Generated by Django 5.0.4 on 2024-04-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сбора')),
                ('occasion', models.CharField(max_length=100, verbose_name='Повод для сбора')),
                ('description', models.TextField(verbose_name='Описание целей сбора')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма запланированная к сбору')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Собранная сумма на текущий момент')),
                ('contributors_count', models.IntegerField(default=0, verbose_name='Колличество сделавших пожертвование')),
                ('cover_image', models.ImageField(upload_to='image/', verbose_name='Обложка сбора')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время завершение сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
            options={
                'verbose_name': 'сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма платежа')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collect.collect', verbose_name='Платеж определенного сбора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший платеж')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платяжи',
                'ordering': ('-datetime',),
            },
        ),
    ]
