# Generated by Django 5.0.4 on 2024-05-01 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Событие для сбора')),
            ],
            options={
                'verbose_name': 'событие сбора',
                'verbose_name_plural': 'События сборов',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сбора')),
                ('text', models.TextField(verbose_name='Описание целей сбора')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Минимально заплонированная сумма сбора - 0.')], verbose_name='Сумма запланированная к сбору')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Минимально собранная сумма сбора - 0.')], verbose_name='Собранная сумма на текущий момент')),
                ('patrician_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимальное количество людей сделавших пожертование - 0.')], verbose_name='Колличество сделавших пожертвование')),
                ('cover', models.ImageField(upload_to='source/image/', verbose_name='Обложка сбора')),
                ('endtime', models.DateTimeField(verbose_name='Дата и время завершение сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
                ('event', models.ManyToManyField(to='collect.event', verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Минимальная сумма платежа - 0.01.')], verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.collect', verbose_name='Платеж сбора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь платежа')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платяжи',
                'ordering': ('-created_at',),
            },
        ),
    ]
