# Generated by Django 5.0.4 on 2024-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='list_payment',
            field=models.ManyToManyField(related_name='related_collects', to='collect.payment', verbose_name='Автор сбора'),
        ),
    ]
