# Generated by Django 5.0.4 on 2024-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Повод для сбора')),
            ],
            options={
                'verbose_name': 'причина сбора',
                'verbose_name_plural': 'Причины сборов',
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='collect',
            name='occasion',
        ),
        migrations.AddField(
            model_name='collect',
            name='occasion',
            field=models.ManyToManyField(to='collect.occasion', verbose_name='Причина'),
        ),
    ]
