# Generated by Django 5.0.4 on 2024-05-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название сбора'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Событие для сбора'),
        ),
    ]
