# Generated by Django 5.0.4 on 2024-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_occasion_remove_collect_occasion_collect_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собранная сумма на текущий момент'),
        ),
    ]
