# Generated by Django 5.0.4 on 2024-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_collect_list_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='list_payment',
            field=models.ManyToManyField(related_name='donations', to='collect.payment', verbose_name='Автор сбора'),
        ),
    ]
