# Generated by Django 5.0.4 on 2024-05-04 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, message='Минимально заплонированная сумма сбора в рублях - 0.01.')], verbose_name='Сумма запланированная к сбору'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01, message='Минимальная сумма платежа в рублях- 0.01.')], verbose_name='Сумма платежа'),
        ),
    ]
