# Generated by Django 5.0.4 on 2024-05-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_collect_list_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0, message='Минимально собранная сумма сбора - 0.0.')], verbose_name='Собранная сумма на текущий момент'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='patrician_count',
            field=models.PositiveIntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Минимальное количество людей сделавших пожертование - 0.0.')], verbose_name='Колличество сделавших пожертвование'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0, message='Минимально заплонированная сумма сбора - 0.0.')], verbose_name='Сумма запланированная к сбору'),
        ),
    ]
