# Generated by Django 5.0.4 on 2024-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_collect_title_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='text',
            field=models.TextField(verbose_name='Описание целей сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(verbose_name='Название сбора'),
        ),
    ]
