# Generated by Django 5.0.4 on 2024-04-29 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_collect_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='contributors_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное количество людей сделавших пожертование - 0.')], verbose_name='Колличество сделавших пожертвование'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='cover_image',
            field=models.ImageField(upload_to='source/image/', verbose_name='Обложка сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Минимально собранная сумма сбора - 0.')], verbose_name='Собранная сумма на текущий момент'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Минимально заплонированная сумма сбора - 0.')], verbose_name='Сумма запланированная к сбору'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Минимальная сумма платежа - 0.01.')], verbose_name='Сумма платежа'),
        ),
    ]
