# Generated by Django 5.0.4 on 2024-05-04 14:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_collect_target_amount_alter_payment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'default_related_name': 'collects', 'ordering': ('-created_at',), 'verbose_name': 'сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='endtime',
            field=models.DateTimeField(verbose_name='Дата завершение сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Минимально заплонированная сумма сбора в рублях - 0.01.')], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Событие'),
        ),
    ]
