# Generated by Django 5.0.4 on 2024-05-02 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_collect_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='list_payment',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='patrician_count',
        ),
        migrations.AlterField(
            model_name='collect',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='source/image/', verbose_name='Обложка сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='event',
            field=models.ManyToManyField(to='collect.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1, message='Минимально заплонированная сумма сбора - 1.')], verbose_name='Сумма запланированная к сбору'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='text',
            field=models.TextField(max_length=30000, verbose_name='Описание целей сбора'),
        ),
    ]
