# Generated by Django 5.0.4 on 2024-05-02 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_remove_collect_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, message='Минимально заплонированная сумма сбора - 1.')], verbose_name='Сумма запланированная к сбору'),
        ),
    ]
