# Generated by Django 5.0.4 on 2024-05-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_alter_collect_target_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'default_related_name': 'payments', 'ordering': ('-created_at',), 'verbose_name': 'платеж', 'verbose_name_plural': 'Платяжи'},
        ),
    ]
